# Generated by Django 3.2.7 on 2021-09-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_deepthought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepthought',
            name='deepThought_text',
            field=models.CharField(max_length=300),
        ),
    ]
